before_script:
  - chmod +x scripts/alpine.sh
  - ./alpine.sh
  - chmod +x scripts/node.sh
  - ./node.sh
  - gem install bundle --no-document

image: ruby:alpine

build:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
  script:
  - cd enjoeat-sp2
  - npm install

test:
  stage: test
  script:
  - cd ..
  - bundle install
  - bundle exec cucumber
  artifacts:
    when: always
    paths:
      - log/report.html