before_script:
  - chmod +x alpine.sh
  - ./alpine.sh
  - chmod +x node.sh
  - ./node.sh
  - gem install bundle --no-document

image: ruby:alpine

build:
  stage: build
  script:
  - cd enjoeat-sp2
  - npm install
  - npm start

test:
  stage: test
  script:
  - cd ..
  - bundle install
  - bundle exec cucumber
  artifacts:
    when: always
    paths:
      - log/report.html